### ISSUE TITLE
'smolok spark submit' should fallback to default `--master=spark://localhost:7077` if no `--master` option is present

### ISSUE THREAD

**Issue by hekonsek** [smolok/smolok#77]
This will be useful for local development, where you use `localhost` master address anyway.

**Comment by ajurasz** [comment]
I added one more think to the mechanism [1]

[1] - https://github.com/smolok/smolok/commit/67203068f11d4fe293d7716e284eedf26e861042#diff-519b3731c0b3c26bafa462d3efdcc120

**Comment by hekonsek** [comment]
Thanks!
