### ISSUE TITLE
Configure spark nodes

### ISSUE THREAD

**Issue by ajurasz** [smolok/smolok#81]
We need to update/create `conf/spark-env.sh' with following values:

a) for master node:
export SPARK_MASTER_IP="xxx"
export SPARK_LOCAL_IP="xxx"

b) for worker node:
export SPARK_LOCAL_IP="xxx"

where xxx is a external IP adress.

**Comment by ajurasz** [comment]
@hekonsek I need fix for this one because work around I done for master and worker is not working for 'smolok spark submit' and I need to set `SPARK_LOCAL_IP` when I want to run `client` deploy mode.

My proposal for handle this one would be to update `start-worker.sh`, `start-master.sh` and `submit.sh` with following code:

`
if [ -z "${SPARK_LOCAL_IP}" ]; then
  export SPARK_LOCAL_IP=${SPARK_LOCAL_IP}
fi
`

I think this should work, what do you think? 
Assign this task to me if you think this approach is ok.

**Comment by hekonsek** [comment]
Actually I think that setting up those options on the Docker level would be fine. Can you give a try to this [1] commit? I have uploaded the most recent Docker image to DockerHub, so just pull the latest 0.0.1-SNAPSHOT.

[1] https://github.com/smolok/smolok/commit/54b6d07a4d99621a3ae5c6f41215cc74b442fc8c

**Comment by ajurasz** [comment]
Yes it works. Thank you.
