### ISSUE TITLE
Optimaze usage of cmd container

### ISSUE THREAD

**Issue by ajurasz** [smolok/smolok#92]
Now each execution of any `smolok` command first starts new `cmd` container, we should reuse existing container and don't create a new one.

**Comment by ajurasz** [comment]
So I found out that it is possible to run transient container i.e. it will be removed after exit with `--rm` parameter like:
`docker run --rm ...`

**Comment by ajurasz** [comment]
@hekonsek I think we could use the same approach to `spark submit` command, can you agree (if yes I will do appropriate changes)

**Comment by hekonsek** [comment]
+1 I didn't know about this option! Cool stuff. Can you use it whenever appropriate? Thanks!
