### ISSUE TITLE
Optimaze usage of submit container

### ISSUE THREAD

**Issue by ajurasz** [smolok/smolok#93]
Same way as in #92 using clean up option [1]

[1] - https://docs.docker.com/engine/reference/run/#/clean-up-rm

**Comment by hekonsek** [comment]
+1

**Comment by ajurasz** [comment]
After re-thinking this should work by default but in the case of any problems it would be still nice to access container log. So by default, we will clean up containers like `cmd` or `submit` (`shell` #83  in future) but you will be still able to override this behavior with `--verbose` option.

**Comment by hekonsek** [comment]
Good point. But maybe `--keep-logs` will be better? `--verbose` indicates the volume of output printed on the screen.

**Comment by ajurasz** [comment]
Agree.
